version: '3'

services:
  energyinsight:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/db:/app/app/db
      - ./logs:/app/logs
      - ./.env:/app/.env
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
      - TZ=Europe/Rome
    restart: unless-stopped
