version: '3'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/db:/app/app/db
    environment:
      - FLASK_APP=run.py
      - FLASK_DEBUG=1
    restart: unless-stopped
